# Generated by Django 4.2.27 on 2026-01-22 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Користувач'), ('assistant', 'Асистент')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.JSONField(help_text="Векторне представлення опису об'єкта")),
                ('model_name', models.CharField(help_text='Назва моделі (Gemini, sentence-transformer)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='properties.property')),
            ],
        ),
    ]
