# Generated by Cursor on 2026-04-16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="properties",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Список ID об'єктів нерухомості, які асистент рекомендував у цьому повідомленні.",
            ),
        ),
    ]

