# Generated by Cursor on 2026-04-16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0002_initial"),
        ("ai", "0002_chatmessage_properties"),
    ]

    operations = []

