# Generated by Django 4.2.27 on 2026-01-22 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(help_text="ID об'єкта з зовнішнього API", unique=True)),
                ('title', models.CharField(help_text='Назва оголошення', max_length=255)),
                ('description', models.TextField(help_text="Опис об'єкта (для LLM та embeddings)")),
                ('price', models.PositiveIntegerField()),
                ('currency', models.CharField(default='$', max_length=10)),
                ('rooms_count', models.PositiveSmallIntegerField(null=True)),
                ('total_area', models.FloatField(null=True)),
                ('living_area', models.FloatField(null=True)),
                ('kitchen_area', models.FloatField(null=True)),
                ('floor', models.PositiveSmallIntegerField(null=True)),
                ('floors_count', models.PositiveSmallIntegerField(null=True)),
                ('building_type', models.CharField(help_text='Тип будинку (цегла, панель тощо)', max_length=50, null=True)),
                ('is_commercial', models.BooleanField(default=False)),
                ('realty_type', models.CharField(choices=[('apartment', 'Квартира'), ('house', 'Будинок'), ('commercial', 'Комерційна нерухомість')], max_length=20)),
                ('sale_type', models.CharField(choices=[('sale', 'Продаж'), ('rent', 'Оренда')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('is_main', models.BooleanField(default=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100, null=True)),
                ('street', models.CharField(max_length=150, null=True)),
                ('building_number', models.CharField(max_length=20, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('metro_station', models.CharField(max_length=100, null=True)),
                ('metro_distance_minutes', models.PositiveSmallIntegerField(null=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='properties.property')),
            ],
        ),
    ]
