# Generated by Django 4.2.27 on 2026-01-22 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='external_id',
        ),
    ]
